/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    QueryBuilder: typeof import('./src/components/QueryBuilder.vue')['default']
    QueryBuilderGroup: typeof import('./src/components/QueryBuilderGroup.vue')['default']
    QueryBuilderRule: typeof import('./src/components/QueryBuilderRule.vue')['default']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VChip: typeof import('vuetify/lib')['VChip']
    VCombobox: typeof import('vuetify/lib')['VCombobox']
    VSelect: typeof import('vuetify/lib')['VSelect']
    VTextField: typeof import('vuetify/lib')['VTextField']
  }
}
